### ISSUE TITLE
invalid operation: 1 << i (shift count type int, must be unsigned integer)

### ISSUE THREAD

**Issue by neboduus** [mason-leap-lab/infinicache#6]
Hi everyone, 
As someone of this community may know, I am trying to move Infinicache from AWS to Knative.
So far I have converted your code in :
- 1 K8s deployment on which the Proxy and the Client are running. Basically I created a container which reflects the original proxy environment and which opens all the requested ports. Moreover 
    * I have saved into `proxy/server/config` a list with my Knative Functions IPs,
    * Saved the IP of each Node into each Deployment that the Scheduler creates
    * Replaced the only function that was using AWS SDK to invoke the Lambdas (`(ins *Instance) triggerLambdaLocked(warmUp bool)`) to perform a HTTP POST to the saved IP instead of using AWS SDK
- 1 Knative Service which runs the Lambda nodes (basically I removed the AWS Lambda handler and replaced it with a http endpoint and of course containerized everything)

I am now trying to connect the 2 components but of course I have many questions:

* I would like to kindly ask what do you think about such mechanism?
* Should I modify other stuff in order to allow proxy to register the nodes?

Moreover i also saw a bad error the last times I was trying to debug some of my changes. When runnning the following code I obtain:
```bash
$ go run client/example/main.go 
# github.com/seiflotfy/cuckoofilter
../pkg/mod/github.com/seiflotfy/cuckoofilter@v0.0.0-20200323075608-c8f23b6b6cef/util.go:17:14: invalid operation: 1 << i (shift count type int, must be unsigned integer)
```

* Do you think is related to some of my changes? I never touched the client library.

Thanks in advance for any help you could provide.

PS If you want you can have a look at my changes in my forked repository https://github.com/neboduus/infinicache/tree/master/proxy

**Comment by zhangjyr** [comment]
I think the error is related to the use of consistent hash rings. May be because you passed some invalid value while interface{} is accepted. Never occurs on our side.

If possible, I would suggest a P2P migration/backup protocol instead using a relay. That should be possible since we have ips in k8s.

**Comment by neboduus** [comment]
In the end the error was from redeo lib, I found the bug, signaled and they fixed it.

**Comment by wangaoone** [comment]
> In the end the error was from redeo lib, I found the bug, signaled and they fixed it.

Would you please point out where the bug is? And did you issue a pull request?

**Comment by neboduus** [comment]
My solution is described in this [issue](https://github.com/seiflotfy/cuckoofilter/issues/30)

Moreover in order to update your project you should cancel the reference to cuckoo filter from `go.mod` and adjust dependencies with `go mod tidy`
