### ISSUE TITLE
Changed economics as of December 2020

### ISSUE THREAD

**Issue by aidansteele** [mason-leap-lab/infinicache#9]
Hi,

Thanks for sharing a very interesting project! As of December, there have been a few changes to AWS Lambda that might be relevant to this project.

* The first is that Lambda now has [per-millisecond billing](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-1ms-billing-granularity-adds-cost-savings/) rather than rounding up to the nearest 100ms. 

* The second is that Lambda can now have [10GB of RAM and 6 vCPUs](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-functions-with-up-to-10-gb-of-memory-and-6-vcpus/).

* Processes in a Lambda can [be notified of shutdown](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-extensions-in-preview/) to perform cleanup.  

* Finally, it also now supports [AVX2](https://aws.amazon.com/blogs/compute/creating-faster-aws-lambda-functions-with-avx2/) which might help with erasure coding.

Does this affect the cost analysis in a material way?

**Comment by wangaoone** [comment]
> Hi,
> 
> Thanks for sharing a very interesting project! As of December, there have been a few changes to AWS Lambda that might be relevant to this project.
> 
> * The first is that Lambda now has [per-millisecond billing](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-1ms-billing-granularity-adds-cost-savings/) rather than rounding up to the nearest 100ms.
> * The second is that Lambda can now have [10GB of RAM and 6 vCPUs](https://aws.amazon.com/blogs/aws/new-for-aws-lambda-functions-with-up-to-10-gb-of-memory-and-6-vcpus/).
> * Processes in a Lambda can [be notified of shutdown](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-extensions-in-preview/) to perform cleanup.
> 
> Does this affect the cost analysis in a material way?

Yes, I believe the 1ms billing cycle can affect Infinicache's cost-effectiveness.

> * Finally, it also now supports [AVX2](https://aws.amazon.com/blogs/compute/creating-faster-aws-lambda-functions-with-avx2/) which might help with erasure coding.

But for the last bullet point, we do not let each lambda node do the erasure coding/decoding related job. So this new technique may not help with the erasure coding. But it worthwhile to have a performance test under the current version of Lambda with those new features.
